#
# This test file has been generated by kwb.test::create_test_files()
# launched by user micha on 2019-09-10 18:15:01.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("assess_bathing_quality_eu() works", {

  expect_error(
    kwb.flusshygiene:::assess_bathing_quality_eu()
    # argument "e.coli" is missing, with no default
  )

})

